title: Kadaster Kaart
author: Sem Postma
email: support@esstudio.site
description: >-
  A list of applications made by ESS.
# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  style: compressed
  sass_dir: _sass


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
